# hyprlock 0.9.x syntax
general {
    hide_cursor = true
}

# ── Background (blur) ───────────────────────────────────────────────
background {
    monitor =
    path = ""
    reload_cmd = echo /home/rinas/.local/share/wallpapers/anime-1.jpg
    reload_time = 3
    blur_size = 8
    blur_passes = 1
}

# ── Large clock ─────────────────────────────────────────────────────
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 120
    font_family = "JetBrainsMono Nerd Font"
    color = rgba(255, 255, 255, 0.9)
    position = 0, 130
    halign = center
    valign = center
}

# input field (default, otherwise you can't type password)
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15
    font_family = "JetBrainsMono Nerd Font"
    placeholder_text = Input password...
    position = 0, -20
    halign = center
    valign = center
}
