# monitors
$monitorA=LVDS-1
$monitorB=VGA-1
# modifiers
$mainMod = SUPER
$altControl = Alt_CTRL
$modA = SUPER_CTRL
$modB = SUPER_SHIFT
$modC = SUPER


# colours
$activeBorder = 33ccffFF
$border = 595959FF


# wallpaper
$wallpaper = street.jpg
$wallpaperDay = island_day.jpg
$wallpaperNight = island_night.jpg
